<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{11a895ac-5a06-4334-87ae-34581a64c27e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	test: BOOL;

END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_FactoryIO_Read_Inputs();
F_FactoryIO_Read_InputRegs();
F_FactoryIO_Write_Coils();
F_FactoryIO_WriteRegs();

test := GAB_FactoryIO_Inputs[0].0;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="14" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="21" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>